---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=0"
      - base=dev
      - label=pronto-pra-merge
    actions:
      merge:
        method: squash
        delete_head_branch:
