pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=dev
      - label=pronto-pra-merge
    actions:
      merge:
        method: squash
