---
name: Clang-format

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{github.event.pull_request.head.ref}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: "src"
          exclude: "src/protobuf"
          extensions: "cpp,hpp,h"
          clangFormatVersion: 14
          inplace: true

      - uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Code format"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
